### ISSUE TITLE
does the return value include a new `id` column

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-covariate-extractor#15]
Is it required? Can we remove before returning?

It's returning this extra column to the `fn-prev-pred` function. In that fn we try to make sure we're not overwriting any existing column named `id`: would be great f we can remove this column on the return in `fn-cov-extr`, instead of handling in the receiver fn

**Comment by HughSt** [comment]
This function doesn't. `fn-prevalence-predictor` I think requires a set of unique IDs. So the shiny app checks for unique IDs and if they don't exist it sticks a _1:_n after each ID value.

**Comment by HughSt** [comment]
`fn-prevalence-predictor` could probably be written without having the reliance on IDs as `fn-covariate-extractor` which is used by `fn-prevalence-predictor` returns the `points` GeoJSON in the same order in which it was passed in. There is therefore no real reason why we need to do any merges, I think. @ric70x7 is that correct?

**Comment by ric70x7** [comment]
Yes, that is correct.

**Comment by HughSt** [comment]
Closing
