### ISSUE TITLE
No error checking for download timeout 

### ISSUE THREAD

**Issue by superuser-chi** [disarm-platform/fn-covariate-extractor#17]
On our slow connection the roads layer never downloaded. We got the following error:
```json
{                                                                                                                      
    "result": "Error in load(\"road_coords_global_combined.RData\"): error reading from connection\n",                 
    "type": "error"                                                                                                    
}
```

**Comment by onlyjsmith** [comment]
Is this when we're running it locally?

I guess the same could still happen with massive files remotely.

I think we should return a better error message if the remote requests timeout.

**Comment by onlyjsmith** [comment]
As of v0.2.0 we now return better error messages if one of the layers fails to download.
