### ISSUE TITLE
Deployed version breaks when 'dist_to_road_m' used

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/fn-covariate-extractor#19]
For some reason, (using the `test_req` file) if you include `dist_to_road_m` in the request, the deployed version returns a 502 error. 

```
Response [https://faas.srv.disarm.io/function/fn-covariate-extractor]
  Date: 2020-01-23 22:00
  Status: 502
  Content-Type: <unknown>
<EMPTY BODY>
```

However, the same input works fine when I test on the containerized version (commit 15a3649) on my machine.

Any ideas?

**Comment by HughSt** [comment]
This might be related to #17 . Guessing the file partially downloaded once and therefore the function thinks it exists and doesn't bother going to get it again.

Guess in the short term we need to make sure it's there. But not sure about how to deal with this issue more generally..

**Comment by onlyjsmith** [comment]
Need to investigate. @TNgidi can you reproduce?

@HughSt partial-downloads should not be an issue now we're using the proper http (Squid) cache.

**Comment by TNgidi** [comment]
I tried to reproduce but I cannot. I will attach an image of the result where I ran it two times without changing anything on the testreq file, you will see the result that `dist_to_road_m` was returned. In the last request I asked it to return on `dist_to_road_m` and it did. 
![Screenshot 2020-01-24 at 9 03 55 AM](https://user-images.githubusercontent.com/36029281/73050562-ef54ae00-3e88-11ea-8888-9a4652fca2b9.png)

**Comment by onlyjsmith** [comment]
@TNgidi thanks. Can you post the test file you used?

**Comment by TNgidi** [comment]
Hope the content is ok as you cant attach json here. I will post it in the next comment.

**Comment by TNgidi** [comment]
```json
{
  "layer_names": [
    "dist_to_road_m"
  ],
  "points": {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "properties": {},
        "geometry": {
          "type": "Point",
          "coordinates": [
            31.39068603515625,
            -26.241692799340115
          ]
        }
      },
      {
        "type": "Feature",
        "properties": {},
        "geometry": {
          "type": "Point",
          "coordinates": [
            31.6680908203125,
            -26.470573022375085
          ]
        }
      },
      {
        "type": "Feature",
        "properties": {},
        "geometry": {
          "type": "Point",
          "coordinates": [
            31.1737060546875,
            -26.645003827815252
          ]
        }
      }
    ]
  }
}
```

**Comment by onlyjsmith** [comment]
Thanks both. That file failed for me the first time, then works.

So, it works sometimes but not others: it feels like it is a caching issue. We're upgrading the cache config at the moment, so might be able to fix it.

**Comment by onlyjsmith** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [change squid config](https://trello.com/c/lzGu3uCT/80-change-squid-config)

**Comment by onlyjsmith** [comment]
Think this is related to a large file being stored on Dropbox - we might be having trouble following redirects.

**Comment by onlyjsmith** [comment]
@HughSt is going to try changing the roads layer file to one on GCS

**Comment by HughSt** [comment]
Think this can be closed?
