### ISSUE TITLE
should the `download` functions persist?

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-covariate-extractor#6]
Are there some options to re-use already downloaded data layers, or is re-downloading every run a simple way to ensure the data is always fresh?

If we re-use layers, we obviously need to make sure they are not outdated.

**Comment by HughSt** [comment]
Absolutely, I just wasn't sure where data was being stored using docker. Can I just treat this as per normal, i.e. check if the file exists, if not download and load into R.

**Comment by HughSt** [comment]
related to #5

**Comment by onlyjsmith** [comment]
Closing for #5
