### ISSUE TITLE
document the input parameters and output format

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-covariate-extractor#7]
At some point, would be good to be have a standardised approach for this, but to start, we could add a `README.md` file to each and just write down what we're thinking.

**Comment by onlyjsmith** [comment]
Example


Input:
- dist_to_rivers: boolean, required
- coords: array of {lat: 12, lng: 34} 

Output:
- count: number

**Comment by HughSt** [comment]
@onlyjsmith We might not completely have standardized this, but think we can close now we have some decent docs for this?

**Comment by onlyjsmith** [comment]
Agree - we've got a SPECS.md file
