### ISSUE TITLE
Trouble deploying to OpenFaas

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/fn-covariate-extractor#8]
I'm having trouble deploying a working version to OpenFaas. I removed the existing version on OpenFaas and then from the terminal (having navigated to the folder containing `stack.yml`) I ran `faas up`. It appears on OpenFaas as 'ready' but when I test with the test_req.json it gives me a 500 error. This seems to happen when trying to deploy any function from my machine. Complete output from that command show below

```
HughBook:fn-covariate-extractor hughsturrock$ faas up
[0] > Building fn-covariate-extractor.
Building: disarm/fn-covariate-extractor:0.0.5 with Dockerfile. Please wait..
Sending build context to Docker daemon  83.97kB
Step 1/14 : FROM rocker/geospatial
 ---> 9f07803e46ee
Step 2/14 : RUN mkdir -p /home/app
 ---> Using cache
 ---> b0f25e842653
Step 3/14 : WORKDIR /app
 ---> Using cache
 ---> 55f82456a63a
Step 4/14 : COPY function/install_packages.R function/
 ---> Using cache
 ---> 73bb61f4b057
Step 5/14 : RUN Rscript function/install_packages.R
 ---> Using cache
 ---> 0d57e1ce7c8f
Step 6/14 : ADD https://github.com/openfaas/faas/releases/download/0.9.14/fwatchdog /usr/bin
Downloading  4.453MB/4.453MB
 ---> Using cache
 ---> 0ab1beb353fb
Step 7/14 : RUN chmod +x /usr/bin/fwatchdog
 ---> Using cache
 ---> a0193a8b43f4
Step 8/14 : COPY main.R .
 ---> Using cache
 ---> f0c38e3f5895
Step 9/14 : COPY function function
 ---> Using cache
 ---> fe09c826ac01
Step 10/14 : ENV fprocess="Rscript main.R"
 ---> Using cache
 ---> 74b249d27a33
Step 11/14 : ENV write_debug="false"
 ---> Using cache
 ---> cf18b3c8b271
Step 12/14 : EXPOSE 8080
 ---> Using cache
 ---> dd9feaa8e7bd
Step 13/14 : HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1
 ---> Using cache
 ---> 55b5efa59b80
Step 14/14 : CMD [ "fwatchdog" ]
 ---> Using cache
 ---> 5a728e1a8493
Successfully built 5a728e1a8493
Successfully tagged disarm/fn-covariate-extractor:0.0.5
Image: disarm/fn-covariate-extractor:0.0.5 built.
[0] < Building fn-covariate-extractor done.
[0] worker done.

[0] > Pushing fn-covariate-extractor [disarm/fn-covariate-extractor:0.0.5].
The push refers to repository [docker.io/disarm/fn-covariate-extractor]
3acd04a61b39: Layer already exists 
431b7455545e: Layer already exists 
ee26a7832730: Layer already exists 
52c7751a8a41: Layer already exists 
01cbd052329f: Layer already exists 
2aa50424a9cb: Layer already exists 
fd9f115c10ca: Layer already exists 
a3684291c86d: Layer already exists 
94368460b478: Layer already exists 
df8463098b5d: Layer already exists 
b7e9b56058ba: Layer already exists 
9f3b934a68a6: Layer already exists 
c9e785a64007: Layer already exists 
f50df112393d: Layer already exists 
5fbfa48f6838: Layer already exists 
4d656ac24084: Layer already exists 
7e2dfde7d806: Layer already exists 
badfbcebf7f8: Layer already exists 
0.0.5: digest: sha256:c67ad3d5cf62b34ff98d3bafcc615043d4a721332c6c62a2c944885489b24106 size: 4093
[0] < Pushing fn-covariate-extractor [disarm/fn-covariate-extractor:0.0.5] done.
[0] worker done.

Deploying: fn-covariate-extractor.

Deployed. 202 Accepted.
URL: https://faas.srv.disarm.io/function/fn-covariate-extractor
```

**Comment by HughSt** [comment]
BTW - I also noticed that on hub.docker.com I was not assigned as a 'builder'. I have assigned myself, but this hasn't resolved the issue.

**Comment by HughSt** [comment]
Also, we weren't sure whether there was a difference between running the command

`faas up` and `fass-cli up`

I have tried both, but doesn't seem to make a difference.

**Comment by ric70x7** [comment]
Here is the error I get (I'm already logged in in openfaas and docker):

fn-covariate-extractor$ sudo faas-cli up
[0] > Building fn-covariate-extractor.
Building: disarm/fn-covariate-extractor:0.0.6 with Dockerfile. Please wait..
Sending build context to Docker daemon  14.34kB
Step 1/14 : FROM rocker/geospatial
 ---> 9f07803e46ee
Step 2/14 : RUN mkdir -p /home/app
 ---> Using cache
 ---> 03268e6bbba5
Step 3/14 : WORKDIR /app
 ---> Using cache
 ---> 8f7f30b1ee45
Step 4/14 : COPY function/install_packages.R function/
 ---> Using cache
 ---> a94be6f6a9b5
Step 5/14 : RUN Rscript function/install_packages.R
 ---> Using cache
 ---> c16bee41850b
Step 6/14 : ADD https://github.com/openfaas/faas/releases/download/0.9.14/fwatchdog /usr/bin
Downloading [==================================================>]  4.453MB/4.453MB
 ---> Using cache
 ---> d521c89f78b3
Step 7/14 : RUN chmod +x /usr/bin/fwatchdog
 ---> Using cache
 ---> 5dc32423ef06
Step 8/14 : COPY main.R .
 ---> Using cache
 ---> a71f1b913842
Step 9/14 : COPY function function
 ---> Using cache
 ---> 16f313f25a0d
Step 10/14 : ENV fprocess="Rscript main.R"
 ---> Using cache
 ---> 51f0366ea92b
Step 11/14 : ENV write_debug="false"
 ---> Using cache
 ---> ed09457b85e1
Step 12/14 : EXPOSE 8080
 ---> Using cache
 ---> 1fdb01032a35
Step 13/14 : HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1
 ---> Using cache
 ---> a6e6b85d943f
Step 14/14 : CMD [ "fwatchdog" ]
 ---> Using cache
 ---> 35a8a6da7e3f
Successfully built 35a8a6da7e3f
Successfully tagged disarm/fn-covariate-extractor:0.0.6
Image: disarm/fn-covariate-extractor:0.0.6 built.
[0] < Building fn-covariate-extractor done.
[0] worker done.

[0] > Pushing fn-covariate-extractor [disarm/fn-covariate-extractor:0.0.6].
The push refers to repository [docker.io/disarm/fn-covariate-extractor]
088893dffe42: Preparing 
d10215d2beaa: Preparing 
eb21767cd01e: Preparing 
e8a0962a2a12: Preparing 
b7bf6b442106: Preparing 
a300a5d7d497: Waiting 
770fa85800c2: Waiting 
418abac4772b: Waiting 
94368460b478: Waiting 
df8463098b5d: Waiting 
b7e9b56058ba: Waiting 
9f3b934a68a6: Waiting 
c9e785a64007: Waiting 
f50df112393d: Waiting 
5fbfa48f6838: Waiting 
4d656ac24084: Waiting 
7e2dfde7d806: Waiting 
badfbcebf7f8: Waiting 
denied: requested access to the resource is denied
2019/03/07 15:16:56 ERROR - Could not execute command: [docker push disarm/fn-covariate-extractor:0.0.6]

**Comment by onlyjsmith** [comment]
Hi guys

- @HughSt I don't see any problems in the first output you posted - looks to have worked perfectly. So I don't think the problem is with the 'deployment': it's likely to be with _what_ you deployed, and possibly the infrastructure. We need to explore both!

- @ric70x7 yours looks like a Docker Hub authentication problem. Can you try to do `docker login` again, and make sure your username is `ric70x7` - just checked and that's the one with _builder_ permissions in the DiSARM Docker Hub team.

- I think `faas up` and `faas-cli up` are the same. If you want to be certain on your machine, typing `faas version && faas-cli version` in the terminal should print the version info twice, and you can check they have the same version and the same hash.

**Comment by onlyjsmith** [comment]
Update for @ric70x7 don't bother logging-in again, just try pushing again. Think it was a permissions issue on Docker Hub - have changed, and should work.

**Comment by HughSt** [comment]
OK, issue solved (for me). The `RANN` package was missing from `install_packages.R`. How this still allowed @onlyjsmith to deploy is a mystery though...

I think @ric70x7 is still having the same error when deploying.
